name: 1.0$(rev:.r)

trigger:
- master
- develop/*
  
parameters:
- name: AgentName
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Linux Agents'
  - 'MS Windows Agents'

variables:
  buildConfiguration: 'Release'
  webProjects: '**/*.csproj'
  terraformFolder: '$(System.DefaultWorkingDirectory)/src/web-samples-appconfig/terraform'
  testProjects: '**/*[Tt]ests/*.csproj'

stages:
  - stage: 'Build'
    pool:
      name: ${{ parameters.AgentName }}
      vmImage: 'ubuntu-latest'
    jobs:  
    - job: 'Bundle'
      
      steps:
      - script: echo $(build.buildNumber)
        displayName: Show build number
        
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(webProjects)
          arguments: '--configuration $(buildConfiguration)'
          
      - task: CopyFiles@2
        displayName: Copy terraform plan artefacts
        inputs: 
          sourceFolder: '$(terraformFolder)'
          contents: |
            **/*.tf
            **/configuration.tfvars
            !**/configuration.auto.tfvars
            !**/versions.tf
          targetFolder: '$(Build.ArtifactStagingDirectory)/terraform'
          cleanTargetFolder: false
          overWrite: false
          flattenFolders: false

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)/website'
          zipAfterPublish: True

      - task: PublishBuildArtifacts@1
        displayName: Publish website artefacts
        inputs:
          PathtoPublish: '$(build.ArtifactStagingDirectory)/website'
          ArtifactName: website
          condition: succeededOrFailed()

      - task: PublishBuildArtifacts@1
        displayName: Publish terraform plan artefacts
        inputs:
          pathToPublish: '$(build.ArtifactStagingDirectory)/terraform'
          artifactName: 'terraform'
          publishLocation: 'container'

      - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@20
        displayName: 'WhiteSource Bolt'